import type { Metadata } from "next";
import { Manrope, Inter } from "next/font/google";
import "./globals.css";
import { MainHeader } from "@/components/ui/MainHeader";
import ConvexClientProvider from "@/components/ConvexClientProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${inter.variable} h-full antialiased dark`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-on-background font-body" suppressHydrationWarning>
        <ConvexClientProvider>
          <MainHeader />

          <main className="flex-1 flex flex-col">
            {children}
          </main>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
